package DictionaryAppJavaSwing;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import com.sun.speech.freetts.*;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thanh
 */
public class DictionaryApplication extends javax.swing.JFrame {
    private static final String VOICENAME = "kevin16";
    DictionaryManagement dictionaryManagement = new DictionaryManagement();
    /**
     * Creates new form DictionaryApplication
     */
    public DictionaryApplication() {
        dictionaryManagement.insertFromFile();
        initComponents();
        setTitle("DictionaryApp"); 
        getContentPane().setBackground(new java.awt.Color(56, 113, 200));
        setResizable(false);
        setLocationRelativeTo(null);   
        showAllWords();
    }
    public void showAllWords() {
        DefaultListModel defaultListModel = new DefaultListModel();
        defaultListModel.addElement(null);
        for(int i = 0; i < Dictionary.words.size(); i++) {
            defaultListModel.addElement(Dictionary.words.get(i).getWord_target());
        }
        jList1.setModel(defaultListModel);
    }
    
    public String showAllDefine(int k) {
        String s = "";
            String str = Dictionary.words.get(k).getWord_explain();
            String[] words = str.split("\\t");
            for (int j = 0; j < words.length; j++) {
                s += words[j] + "\n";
        }
        return s;
    }
    public static int binarySearch(String word) {
        int left = 0;
        int right = Dictionary.words.size() - 1;
        while (left <= right) {
            int mid = (left + right) / 2;
            if (Dictionary.words.get(mid).getWord_target().compareTo(word) == 0) {
                return mid;
            } else if (Dictionary.words.get(mid).getWord_target().compareTo(word) < 0) {
                left = mid + 1;
            } else {
                right = mid - 1;
            }
        }
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDeFine = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jPortSearch = new javax.swing.JTextField();
        jSearch = new javax.swing.JButton();
        jSpeak = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jExit = new javax.swing.JButton();
        jClear = new javax.swing.JButton();
        jAlterWord = new javax.swing.JButton();
        jRemoveWord = new javax.swing.JButton();
        jAddWord = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jEngVi = new javax.swing.JMenuItem();
        jViEng = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(56, 113, 200));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(56, 113, 200));

        jDeFine.setBackground(new java.awt.Color(153, 153, 255));
        jDeFine.setColumns(20);
        jDeFine.setRows(5);
        jScrollPane1.setViewportView(jDeFine);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(56, 113, 200));

        jList1.setBackground(new java.awt.Color(153, 153, 255));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                jList1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(56, 113, 200));

        jPortSearch.setBackground(new java.awt.Color(153, 153, 255));
        jPortSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPortSearchActionPerformed(evt);
            }
        });
        jPortSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                jPortSearchKeyPressed(evt);
            }
            public void keyReleased(KeyEvent evt) {
                jPortSearchKeyReleased(evt);
            }
        });

        jSearch.setBackground(new java.awt.Color(153, 153, 255));
        jSearch.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        jSearch.setForeground(new java.awt.Color(51, 51, 255));
        jSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jSearch.setText("Search");
        jSearch.setBorder(new javax.swing.border.MatteBorder(null));
        jSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchMouseClicked(evt);
            }
        });
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });

        jSpeak.setBackground(new java.awt.Color(153, 153, 255));
        jSpeak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/speech.png"))); // NOI18N
        jSpeak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpeakMouseClicked(evt);
            }
        });
        jSpeak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpeakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPortSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpeak, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPortSearch)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSpeak, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(jSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(56, 113, 200));

        jExit.setBackground(new java.awt.Color(153, 153, 255));
        jExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        jClear.setBackground(new java.awt.Color(153, 153, 255));
        jClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        jClear.setText("Clear");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });

        jAlterWord.setBackground(new java.awt.Color(153, 153, 255));
        jAlterWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shuffle.png"))); // NOI18N
        jAlterWord.setText("Sửa");
        jAlterWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAlterWordMouseClicked(evt);
            }
        });
        jAlterWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterWordActionPerformed(evt);
            }
        });

        jRemoveWord.setBackground(new java.awt.Color(153, 153, 255));
        jRemoveWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jRemoveWord.setText("Xóa");
        jRemoveWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRemoveWordMouseClicked(evt);
            }
        });
        jRemoveWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveWordMousePerformed(evt);
            }
        });

        jAddWord.setBackground(new java.awt.Color(153, 153, 255));
        jAddWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        jAddWord.setText("Thêm ");
        jAddWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddWordMouseClicked(evt);
            }
        });
        jAddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddWordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAddWord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRemoveWord, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAlterWord, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRemoveWord, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAddWord, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAlterWord, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(56, 113, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/translate (1).png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/contacts-book.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/setting.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(56, 113, 200));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logoz.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu5.setText(" Translate");

        jEngVi.setText("Eng-Vi Dictionary");
        jEngVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEngViActionPerformed(evt);
            }
        });
        jMenu5.add(jEngVi);

        jViEng.setText("Vi-Eng Dictionary");
        jViEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViEngActionPerformed(evt);
            }
        });
        jMenu5.add(jViEng);

        jMenuBar1.add(jMenu5);
        jMenu5.getAccessibleContext().setAccessibleDescription("");

        jMenu3.setText("       Contact    ");

        jMenuItem2.setText("    Nhóm 10");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("   Settings   ");

        jMenu6.setText("Font Background");

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("Ariel");
        jRadioButtonMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jRadioButtonMenuItem5);

        jRadioButtonMenuItem6.setSelected(true);
        jRadioButtonMenuItem6.setText("Times New Roman");
        jRadioButtonMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jRadioButtonMenuItem6);

        jMenu2.add(jMenu6);

        jMenu7.setText("Color Background");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Default");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Green Blue");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Orange");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem3);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchActionPerformed

    private void jAddWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddWordActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        String wordSearch = jList1.getSelectedValue();
        int i = binarySearch(wordSearch);   
        jPortSearch.setText(Dictionary.words.get(i).getWord_target());
        jDeFine.setText(showAllDefine(i));    
        
    }//GEN-LAST:event_jList1MouseClicked

    private void formKeyTyped(KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formKeyTyped

    private void jPortSearchKeyReleased(KeyEvent evt) {//GEN-FIRST:event_jPortSearchKeyReleased
        // TODO add your handling code here:\
        DefaultListModel defaultListModel = new DefaultListModel();
        defaultListModel.removeAllElements();
        jDeFine.setText("");
        defaultListModel.addElement(null);
        String wordType = jPortSearch.getText();
        for (int i = 0; i < Dictionary.words.size(); i++) {
            if (Dictionary.words.get(i).getWord_target().startsWith(wordType)) {
                defaultListModel.addElement(Dictionary.words.get(i).getWord_target());
            }
        }
        jList1.setModel(defaultListModel);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int i = binarySearch(wordType);
            if (i != -1) {
                jDeFine.setText(showAllDefine(i));    
                } else {
                JOptionPane.showMessageDialog(rootPane, "Không có từ nào để hiển thị!");
            }
        }
        if (wordType.equals("")) {
            defaultListModel.removeAllElements();
            jDeFine.setText("");
            showAllWords();
        }
    }//GEN-LAST:event_jPortSearchKeyReleased

    private void jSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchMouseClicked
        // TODO add your handling code here:
        String wordType = jPortSearch.getText();
        int i = binarySearch(wordType);   
        if (i != -1) {
                jDeFine.setText(showAllDefine(i));    
                } else {
                JOptionPane.showMessageDialog(rootPane, "Không có từ nào để hiển thị!");
            }
    }//GEN-LAST:event_jSearchMouseClicked

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn chắc chắn muốn thoát chương trình?");
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jExitActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        // TODO add your handling code here:
        jPortSearch.setText("");
        jDeFine.setText("");
        showAllWords();
    }//GEN-LAST:event_jClearActionPerformed

    private void jPortSearchKeyTyped(KeyEvent evt) {//GEN-FIRST:event_jPortSearchKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPortSearchKeyTyped

    private void jPortSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPortSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPortSearchActionPerformed

    private void jPortSearchKeyPressed(KeyEvent evt) {//GEN-FIRST:event_jPortSearchKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPortSearchKeyPressed

    private void jRemoveWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRemoveWordMouseClicked
         RemoveWordtoApp removeWordtoApp = new RemoveWordtoApp();
         removeWordtoApp.setVisible(true);
    }//GEN-LAST:event_jRemoveWordMouseClicked

    private void jAlterWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlterWordActionPerformed

    private void jRemoveWordMousePerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveWordMousePerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRemoveWordMousePerformed

    private void jSpeakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpeakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpeakActionPerformed

    private void jSpeakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpeakMouseClicked
        // TODO add your handling code here:
        System.setProperty("freetts.voices", "com.sun.speech.freetts.en.us.cmu_us_kal.KevinVoiceDirectory");
        Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice(VOICENAME);
        voice.allocate();
        try{
            voice.speak(jPortSearch.getText());
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jSpeakMouseClicked

    private void jList1KeyReleased(KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased
        // TODO add your handling code here:
        String wordSearch = jList1.getSelectedValue();
        int i = binarySearch(wordSearch);   
        jPortSearch.setText(Dictionary.words.get(i).getWord_target());
        jDeFine.setText(showAllDefine(i));
    }//GEN-LAST:event_jList1KeyReleased

    private void jAddWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddWordMouseClicked
        // TODO add your handling code here:
        AddWordtoApp addWordtoApp = new AddWordtoApp();
        addWordtoApp.setVisible(true);
    }//GEN-LAST:event_jAddWordMouseClicked

    private void jAlterWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAlterWordMouseClicked
        // TODO add your handling code here:
        AlterWordtoApp alterWordtoApp = new AlterWordtoApp();
        alterWordtoApp.setVisible(true);
    }//GEN-LAST:event_jAlterWordMouseClicked

    private void jViEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViEngActionPerformed
        // TODO add your handling code here:
        ViEngDictionary viEngDictionary = new ViEngDictionary();
        viEngDictionary.setVisible(true);
    }//GEN-LAST:event_jViEngActionPerformed

    private void jEngViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEngViActionPerformed
        // TODO add your handling code here:
        GoogleAPItoApp googleAPItoApp = new GoogleAPItoApp();
        googleAPItoApp.setVisible(true);
    }//GEN-LAST:event_jEngViActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
        getContentPane().setBackground(new java.awt.Color(56, 113, 200));
         jPanel1.setBackground(new java.awt.Color(56, 113, 200));
         jPanel2.setBackground(new java.awt.Color(56, 113, 200));
         jPanel3.setBackground(new java.awt.Color(56, 113, 200));
         jPanel4.setBackground(new java.awt.Color(56, 113, 200));
         jPanel5.setBackground(new java.awt.Color(56, 113, 200));
         jPanel6.setBackground(new java.awt.Color(56, 113, 200));
         jList1.setBackground(new java.awt.Color(153, 153, 255));
         jList2.setBackground(new java.awt.Color(153, 153, 255));
         jAddWord.setBackground(new java.awt.Color(153, 153, 255));
         jAlterWord.setBackground(new java.awt.Color(153, 153, 255));
         jRemoveWord.setBackground(new java.awt.Color(153, 153, 255));
         jClear.setBackground(new java.awt.Color(153, 153, 255));
         jExit.setBackground(new java.awt.Color(153, 153, 255));
         jPortSearch.setBackground(new java.awt.Color(153, 153, 255));
         jDeFine.setBackground(new java.awt.Color(153, 153, 255));
         jSearch.setBackground(new java.awt.Color(153, 153, 255));
         jSpeak.setBackground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        // TODO add your handling code here:
        getContentPane().setBackground(new java.awt.Color(56, 113, 200));//0 255 0
         jPanel1.setBackground(new java.awt.Color(56, 113, 200));
         jPanel2.setBackground(new java.awt.Color(56, 113, 200));
         jPanel3.setBackground(new java.awt.Color(56, 113, 200));
         jPanel4.setBackground(new java.awt.Color(56, 113, 200));
         jPanel5.setBackground(new java.awt.Color(56, 113, 200));
         jPanel6.setBackground(new java.awt.Color(56, 113, 200));
         jList1.setBackground(new java.awt.Color(0, 178, 191));
         jList2.setBackground(new java.awt.Color(0, 178, 191));
         jAddWord.setBackground(new java.awt.Color(0, 178, 191));
         jAlterWord.setBackground(new java.awt.Color(0, 178, 191));
         jRemoveWord.setBackground(new java.awt.Color(0, 178, 191));
         jClear.setBackground(new java.awt.Color(0, 178, 191));
         jExit.setBackground(new java.awt.Color(0, 178, 191));
         jPortSearch.setBackground(new java.awt.Color(0, 178, 191));
         jDeFine.setBackground(new java.awt.Color(0, 178, 191));
         jSearch.setBackground(new java.awt.Color(0, 178, 191));
         jSpeak.setBackground(new java.awt.Color(0, 178, 191));
         
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        // TODO add your handling code here:
        getContentPane().setBackground(new java.awt.Color(56, 113, 200));//0 255 0
         jPanel1.setBackground(new java.awt.Color(56, 113, 200));
         jPanel2.setBackground(new java.awt.Color(56, 113, 200));
         jPanel3.setBackground(new java.awt.Color(56, 113, 200));
         jPanel4.setBackground(new java.awt.Color(56, 113, 200));
         jPanel5.setBackground(new java.awt.Color(56, 113, 200));
         jPanel6.setBackground(new java.awt.Color(56, 113, 200));
        jList1.setBackground(new java.awt.Color(255, 165, 79));
        jList2.setBackground(new java.awt.Color(255, 165, 79));
        jAddWord.setBackground(new java.awt.Color(255, 165, 79));
        jAlterWord.setBackground(new java.awt.Color(255, 165, 79));
        jRemoveWord.setBackground(new java.awt.Color(255, 165, 79));
        jClear.setBackground(new java.awt.Color(255, 165, 79));
        jExit.setBackground(new java.awt.Color(255, 165, 79));
        jPortSearch.setBackground(new java.awt.Color(255, 165, 79));
        jSearch.setBackground(new java.awt.Color(255, 165, 79));
        jSpeak.setBackground(new java.awt.Color(255, 165, 79));
        jDeFine.setBackground(new java.awt.Color(255, 165, 79));
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void jRadioButtonMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem5ActionPerformed
        // TODO add your handling code here:
        jAddWord.setFont(new Font("Ariel", Font.PLAIN, 13));
        jAlterWord.setFont(new Font("Ariel", Font.PLAIN, 13));
        jRemoveWord.setFont(new Font("Ariel", Font.PLAIN, 13));
        jClear.setFont(new Font("Ariel", Font.PLAIN, 13));
        jExit.setFont(new Font("Ariel", Font.PLAIN, 13));
        jSearch.setFont(new Font("Ariel", Font.PLAIN, 15));
        jList1.setFont(new Font("Ariel", Font.PLAIN, 13));
        jList2.setFont(new Font("Ariel", Font.PLAIN, 13));
        jPortSearch.setFont(new Font("Ariel", Font.PLAIN, 13));
        jDeFine.setFont(new Font("Ariel", Font.PLAIN, 13));
    }//GEN-LAST:event_jRadioButtonMenuItem5ActionPerformed

    private void jRadioButtonMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem6ActionPerformed
        // TODO add your handling code here:
        jAddWord.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        jAlterWord.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        jRemoveWord.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        jClear.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        jExit.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        jSearch.setFont(new Font("Times New Roman", Font.PLAIN, 17));
        jList1.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        jList2.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        jPortSearch.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        jDeFine.setFont(new Font("Times New Roman", Font.PLAIN, 14));
    }//GEN-LAST:event_jRadioButtonMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Phạm Minh Thành\nNguyễn Xuân Lâm");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddWord;
    private javax.swing.JButton jAlterWord;
    private javax.swing.JButton jClear;
    private javax.swing.JTextArea jDeFine;
    private javax.swing.JMenuItem jEngVi;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jPortSearch;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JButton jRemoveWord;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jSearch;
    private javax.swing.JButton jSpeak;
    private javax.swing.JMenuItem jViEng;
    // End of variables declaration//GEN-END:variables
}
